/**
 * Theme tokens copied verbatim from the Stitch design export
 * (design-reference/<screen>/code.html → tailwind.config).
 * Do not change values here without updating the design reference.
 */
const FONT_STACK = ['"Roboto Flex Variable"', '"Roboto Flex"', 'Roboto', 'system-ui', 'sans-serif'];
const TYPE_TOKENS = [
  'title-md', 'label-sm', 'body-md', 'headline-sm', 'label-lg', 'headline-lg', 'body-lg',
  'body-sm', 'display-lg-mobile', 'display-lg', 'label-md', 'headline-md', 'title-lg', 'title-sm',
];

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#eff4ff',
        'on-surface': '#0b1c30',
        'inverse-surface': '#213145',
        'surface-container-high': '#dce9ff',
        'surface-tint': '#3051d2',
        'surface-bright': '#f8f9ff',
        'on-primary-fixed': '#001355',
        'on-background': '#0b1c30',
        'surface-container-lowest': '#ffffff',
        tertiary: '#8c0024',
        'tertiary-fixed': '#ffdada',
        'on-tertiary-fixed': '#40000b',
        'primary-container': '#2c4ecf',
        'inverse-primary': '#b8c3ff',
        'inverse-on-surface': '#eaf1ff',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#dde1ff',
        'on-secondary-fixed': '#00210e',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#00522b',
        'on-error-container': '#93000a',
        'on-primary-container': '#cad1ff',
        'surface-dim': '#cbdbf5',
        'secondary-container': '#7ff8a8',
        'surface-container': '#e5eeff',
        'on-tertiary-container': '#ffc5c6',
        'outline-variant': '#c4c5d7',
        primary: '#0033b6',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#64dd91',
        background: '#f8f9ff',
        'surface-variant': '#d3e4fe',
        outline: '#747686',
        'primary-fixed-dim': '#b8c3ff',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#82faab',
        'on-primary-fixed-variant': '#0636ba',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#910526',
        'tertiary-container': '#ae2239',
        'on-surface-variant': '#444654',
        'surface-container-highest': '#d3e4fe',
        surface: '#f8f9ff',
        'on-secondary-container': '#00723d',
        secondary: '#006d3a',
        'tertiary-fixed-dim': '#ffb3b5',
        error: '#ba1a1a',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        'margin-desktop': '3rem',
        'space-xs': '0.25rem',
        margin: '1rem',
        'margin-tablet': '2rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-xl': '2rem',
        'space-lg': '1.5rem',
        'gutter-desktop': '1.5rem',
        'gutter-tablet': '1.5rem',
        gutter: '1rem',
      },
      fontFamily: Object.fromEntries(TYPE_TOKENS.map((k) => [k, FONT_STACK])),
      fontSize: {
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.15px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '0px', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.4px', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.2px', fontWeight: '500' }],
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '0px', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '28px', letterSpacing: '0px', fontWeight: '500' }],
        'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
